# Generated by Django 5.0.3 on 2024-08-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_marks_register_model_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud_registration_model',
            old_name='Clas',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='stud_registration_model',
            old_name='your_reister_no_is',
            new_name='your_register_no_is',
        ),
    ]
